import Head from 'next/head'
import Aside from './Aside'
import { LayoutProps } from '@/types/props.type'

export default function Layout({ children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>ChatGPT Clone</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex flex-col min-h-screen md:flex-row'>
        <Aside />
        {children}
      </div>
    </>
  )
}
